In [1]:
import numpy as np
import scipy as sp

import pandas as pd

import pingouin as pg

In [3]:
#  fig 1c

contra = [94.0812379, 95.2991453, 89.7727273, 95.4022989, 94.3661972]
cre = [3.30284553, 5.395189, 20.8333333, 5.26315789, 0]


res = pg.mwu(cre, contra)
res

     U-val alternative     p-val  RBC  CLES
MWU    0.0   two-sided  0.007937 -1.0   0.0

In [6]:
# fig 1 e

delta_cre = [60.1,
    55.3,
    64.7,
    56.6,
    16.3,
    41,
    61.3,
    40.4,
    65.9,
    50.4,
    41.8,
    77,
    75.3,
    44.9,
    28.8,
    120,
    1,
    -65.1,
    19.4]

cre = [8.2,
    8.1,
    48.8,
    4.2,
    -82.9,
    -120,
    51,
    63.2,
    97.7,
    102.7,
    -119.6,
    -20.9,
    2,
    -120,
    53.6,
    65,
    -119.3,
    75.9,
    -23,
    -41.3,
    -36.5,
    -84.4,
    14.2,
    24.3]

res = pg.mwu(cre, delta_cre)
res

     U-val alternative     p-val       RBC      CLES
MWU  129.0   two-sided  0.015997 -0.434211  0.282895